### ISSUE TITLE
Investigate TestRetry failures

### ISSUE THREAD

**Issue by mattmoor** [knative/net-kourier#30]
This test has been failing consistently enough during nightly testing that it has blocked every single nightly release thus far.

I'm opening this to accompany a TODO next to the logic that skips this.

**Comment by davidor** [comment]
For some reason it fails on the nightly builds, but it looks like it never fails on PRs :thinking:

**Comment by mattmoor** [comment]
Yeah, IDK what's going on, I'm just trying to unblock the releases :)

cc @chizhg @chaodaiG

**Comment by davidor** [comment]
@mattmoor I just realized that the `hack/update-deps.sh` script does not download the conformance tests to `vendor/knative.dev/serving/test/conformance/ingress`. We just have one file in that directory, `util.go`. I wonder if that might be part of the problem.

**Comment by mattmoor** [comment]
That's odd and we should fix it, but I don't think that's our problem since it's flaky 🤔

**Comment by chizhg** [comment]
This is probably related to Go modules. When the test flow runs `go test`, it does not have `-mod=vendor` and causes it to download the dependencies every time.

I don't have enough background to dig out the root cause here, but one difference between CI tests and presubmit tests is - CI tests run build tests, unit tests and integration tests in a row, but the presubmit test runs them separately. Knative client is also using Go modules, and it has some change related to `-mod=vendor` in https://github.com/knative/client/blob/master/test/presubmit-tests.sh#L56.

**Comment by davidor** [comment]
@mattmoor It looks like #33 fixed the issue.
Let me know when we can revert #31 . We'll need to wait for the next nightly, right?

**Comment by mattmoor** [comment]
Let’s wait until after the release cut to be safe.  I’m not completely sure this was why the retry was failing, but if it was then that’d be nice and easy 🤘

**Comment by davidor** [comment]
#33 fixed the issue and the test was re-enabled in #35

**Comment by jmprusi** [comment]
closed by #33

**Comment by jmprusi** [comment]
@mattmoor we don't have perms to close the issue. There's a way to do it via a bot?
